excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://ZeroVirusi.github.io
title: ZeroVirusi
tagline: Antivirus &#537;i securitate IT
description: Blog despre antivirus, securitate IT, recuperare date, tutoriale
paginate: 15